// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCgBsjZ1u_OJ4H3XGk5hlgXW0OGTsCdfs',
    appId: '1:144463087101:web:fe0c9be5cb0a0475554594',
    messagingSenderId: '144463087101',
    projectId: 'granapp-6dcc0',
    authDomain: 'granapp-6dcc0.firebaseapp.com',
    storageBucket: 'granapp-6dcc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgugLr0E7KH-KZOmAJzR00XZpWp6pp7gk',
    appId: '1:144463087101:android:54c5c015708e3174554594',
    messagingSenderId: '144463087101',
    projectId: 'granapp-6dcc0',
    storageBucket: 'granapp-6dcc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFRLUeqaWB2_f7pWO2uNzDGRTX01n6Xw8',
    appId: '1:144463087101:ios:07af1d3bda12b4bf554594',
    messagingSenderId: '144463087101',
    projectId: 'granapp-6dcc0',
    storageBucket: 'granapp-6dcc0.appspot.com',
    iosBundleId: 'com.example.granApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFRLUeqaWB2_f7pWO2uNzDGRTX01n6Xw8',
    appId: '1:144463087101:ios:130551eb0a8d23a5554594',
    messagingSenderId: '144463087101',
    projectId: 'granapp-6dcc0',
    storageBucket: 'granapp-6dcc0.appspot.com',
    iosBundleId: 'com.example.granApp.RunnerTests',
  );
}
